### ISSUE TITLE
There are more pad modes available for selection

### ISSUE THREAD

**Issue by riban-bw** [giezu/LaunchkeyMiniMK3#1]
The spreadsheet describes three pad modes that may be selected by sending CC 3 to the control port. I found a few more.

Value 7 gives a row of toggle buttons, sending CC value 127 when pressed then value 0 when pressed again plus a row of press to hold that send value 127 when pressed and 0 when released.

Value 8 gives a program change selector with 16 mutually exclusive buttons. When one is pressed it selects that button, deselects all other buttons and sends a program change 1-16 depending on which button is pressed.

Both of these send messages to MIDI port 1.

Having selected one of these, it becomes the _Custom_ layout availabe from the Shift+Custom key combination. I haven't checked all values so there _may_ be more. These were available after updating firmware to 1.1. I did not check with firmware 1.01.

**Comment by giezu** [comment]
Really nice discovery! Looks like it's some undocumented, maybe work in progress features?
Found one more, value 6 gives you something similar to drum mode, but notes are in ascending from bottom left to top right corner.
I will add these to README and spreadsheet.

**Comment by riban-bw** [comment]
We all love a bit of kudos! The readme has the wrong text for my github username. Should be riban-bw.

**Comment by giezu** [comment]
Hi! I'm so sorry for the typo, fixed it right now. Thanks for your help!
